[env:thinknode-m9]
board = esp32s3
board_build.arduino.memory_type = qio_opi
board_build.partitions = partitions_16MB_m9.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216

build_src_filter = ${env.build_src_filter} +<../boards/thinknode-m9>

build_flags =
	${env.build_flags}
	-DTHINKNODE_M9
    -DBOARD_HAS_PSRAM
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DDEVICE_NAME='"Elecrow ThinkNode M9"'
	-DOTA_TAG='"thinknode-m9"'
	-DLAUNCHER_DEFAULT_SPIFFS_THRESHOLD=0x500000
	-DHAS_KEYBOARD=1
	-DROTATION=1

	; FreeRTOS Watchdog config for AsyncTCP
	-DCONFIG_ESP_TASK_WDT_TIMEOUT_S=5

	; Power Gate & Backlight Control
	-DPWR_GATE_PIN=18
	-DTFT_BL=17

	; Display (ST7789 240x320 IPS on ThinkNode M9)
	-DTFT_DATABUS_N=0
	-DTFT_DISPLAY_DRIVER_N=1
	-DTFT_WIDTH=240
	-DTFT_HEIGHT=320
	-DTFT_MOSI=11
	-DTFT_SCLK=12
	-DTFT_CS=10
	-DTFT_DC=9
	-DTFT_RST=14
	-DTFT_ROTATION=1
	-DTFT_IPS=1
	-DTFT_COL_OFS1=0
	-DTFT_ROW_OFS1=0
	-DTFT_COL_OFS2=0
	-DTFT_ROW_OFS2=0

	; SD Card Configuration
	-DSDCARD_CS=34
	-DSDCARD_SCK=36
	-DSDCARD_MISO=37
	-DSDCARD_MOSI=35

	; Keyboard (I2C co-processor)
	-DKEYBOARD_SDA=47
	-DKEYBOARD_SCL=48
	-DKEYBOARD_INT=21
	-DKEYBOARD_ADDR=0x5F

lib_deps =
	${env.lib_deps}

lib_ignore =
	SensorLib
	XPowersLib
